### ISSUE TITLE
Calculator: Negative explonents are calculated incorrectly

### ISSUE THREAD

**Issue by pafcu** [duckduckgo/zeroclickinfo-goodies#1694]
[1\*1e1](https://duckduckgo.com/?q=1*%281e-1%29&t=ffcm&ia=answer) gives 10, but [1\*1e-1](https://duckduckgo.com/?q=1*%281e-1%29&t=ffcm&ia=answer) gives 1.71828182845905

It seems like in the latter case the "e" is interpreted as the mathematical constant, not exponential notation.

------
IA Page:  http://duck.co/ia/view/calculator

**Comment by moollaza** [comment]
@pafcu thanks for pointing this out! We'll take a look..

**Comment by GuiltyDolphin** [comment]
This should be fixed now (from PR #1866).

**Comment by mintsoft** [comment]
Thanks @GuiltyDolphin

**Comment by marnix** [comment]
Just a note: this bug was closed Dec 9th, but at this moment still shows up on https://duck.co/ia/dev/issues.  No idea where to report that meta-bug... :-)

**Comment by GuiltyDolphin** [comment]
@marnix, @moollaza, @mintsoft Yeah, I've noticed this too for many of the IA's how often are the pages updated?

**Comment by moollaza** [comment]
I think there were some bugs that the team is fixing to make sure these update much quicker. They should be fixed soon
