### ISSUE TITLE
Negative degree conversion to Kelvins do not work

### ISSUE THREAD

**Issue by Bujiraso** [duckduckgo/zeroclickinfo-goodies#1729]
When converting from degree scales (e.g. `55C in Fahrenheit`), if negative numbers are used while converting **to** Kelvins, no instant answer appears to be triggered, and incorrect results are shown
![negativetokelvin](https://cloud.githubusercontent.com/assets/1975771/10869980/ab253796-8095-11e5-8847-1b8af350e75e.png)

Conversions **from** Kelvins work -- including no answer shown for negative Kelvin (non-sensical) input.

Conversions of positive degrees to Kelvins and conversions between Celsius and Fahrenheit all work well, even with negative numbers. 
![negativetof](https://cloud.githubusercontent.com/assets/1975771/10869998/19201edc-8096-11e5-8cc6-194453318cd0.png)

**Comment by mintsoft** [comment]
@Bujiraso Thanks for the report, I've had a quick look into what's going on here and it looks like there's an issue within Convert::Pluggable that's causing this behaviour. I'll see if I can dig through it again and track it down later on

cc @elohmrow

**Comment by elohmrow** [comment]
@mintsoft what version of C::P is currently in use? i recall a (possibly) similar issue recently https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1413#issuecomment-141917103 ...

**Comment by elohmrow** [comment]
@mintsoft it seems most problems with C::P come from the temperature conversions ... i think my strategy of first converting Y to F then from F to X has some logical hole(s) somewhere.  it may be better for now to simply re-write that routine in C::P using something like http://search.cpan.org/~mopy/Convert-Temperature-0.03/lib/Convert/Temperature.pm for now.  i will implement that w/n 24 hrs and release a new C::P if you think my assessment is more or less accurate.

**Comment by mintsoft** [comment]
@elohmrow I think it's 0.030; I've just upgraded to that on my dev environment and issue still persists.

WRT to temperature conversion, there *shouldn't* be any technical problem with going via another unit. For example Kelvin is the SI unit of temperature and is an absolute measure of temperature (i.e. 0K is 'no kinetic energy of particles'), whilst Celsius & Fahrenheit are standardised around other things. So practically, it should be acceptable to always convert anything into Kelvin and then back to another unit, this is true of any other unit (Fahrenheit for example) as long as the appropriate accuracy is maintained throughout the conversion.

I guess ultimately whatever approach is used we should definitely improve the test coverage of both Conversions and C::P, we only seem to have:
```
'factor' => '5', 'from_unit' => 'kelvin', 'to_unit' => 'fahrenheit', 
'factor' => '5', 'from_unit' => 'f', 'to_unit' => 'celsius',
'factor' => '-5', 'from_unit' => 'kelvin', 'to_unit' => 'fahrenheit',
'factor' => '-123', 'from_unit' => 'celsius', 'to_unit' => 'kelvin'
```
In C::P and 
```
    'convert 5 kelvin to fahrenheit'
    'convert 5 f to celsius'
    '12 degrees Celsius to Fahrenheit'
    '1 degrees Fahrenheit to celsius'
    'how much is 40 kelvin in celsius'
    'how much is 40 kelvin in celsius?'
    'convert -5 kelvin to fahrenheit' => undef,
```
in Conversions. I'll put a suite of more thorough tests around Conversions in a minute and put them into a branch so we can see where we're missing out

**Comment by elohmrow** [comment]
@mintsoft yes, the test suite needs work.  i'm actually at the beginning of a pretty substantial re-write anyway, so this is a good start.  let me know what i can do to best help.  thanks!

**Comment by mintsoft** [comment]
Related: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1731

**Comment by elohmrow** [comment]
all C::P issues should be fixed as of 0.032x

@moollaza @mintsoft

**Comment by Bujiraso** [comment]
I'm still seeing negative conversions not working -- should these be fixed? Are they fixed for others?

**Comment by mintsoft** [comment]
@Bujiraso it's been closed because it's been merged but not deployed yet

**Comment by Bujiraso** [comment]
Thanks @mintsoft :+1:
